### ISSUE TITLE
Support for 429 Too Many Requests error

### ISSUE THREAD

**Issue by ghostapps1** [Shopify/pyactiveresource#25]
The package should catch a 429 error and raise an exception that can be caught by applications using this code

**Comment by hngnaig** [comment]
@ghostapps https://github.com/Shopify/pyactiveresource/blob/master/pyactiveresource/connection.py#L415

raise 429 status code

**Comment by 0ptimusrhyme** [comment]
Closing this, since as noted, this can be handled via `ClientError`.
